### PR TITLE
fix(2720): Jobs fetch query for pull request sync fails

### PR DESCRIPTION
**Pull request by itleigns**
## Context
The following error occurs even after #548.
`negative substring length not allowed`

negative_error

## Objective
We update the raw SQL queries to prevent the error. 

## References
As the following documentation shows, in postgresql, bool expressions are not always evaluated from the left.
https://www.postgresql.org/docs/14/sql-expressions.html#SYNTAX-EXPRESS-EVAL

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by itleigns** [comment]
PR build does not work because `negative substring length not allowed` error occurs.

**Comment by sagar1312** [comment]
@itleigns You are noticing this error against which database?

**Review by tkyi — APPROVED** [review]

**Comment by itleigns** [comment]
I notice this error against the following pipeline.
`https://cd.screwdriver.cd/pipelines/9/`.
So PostgreSQL is used.
Kumada626 took this picture.

**Comment by sagar1312** [comment]
I believe the changes proposed in this PR may not fix the issue.
I have ran the query (pull request sync API) against few pipelines and it works as expected.

I suspect, few of the pipelines associated with screwdriver projects have some archived jobs (now archived) with name prefixed with `PR-` but does not match the latest format for PR job names `PR-<PR_NUMBER>:<PARENT_JOB_NAME>`.

**Comment by itleigns** [comment]
@sagar1312 
I understand.
I would appreciate it if you could delete the non pull request job starting with `PR-` from database.

According to the documentation I put in the references, it looks like the current query is not guaranteed to work.
Is there any reason to leave it as it is now?

**Comment by sagar1312** [comment]
The still exist with this fix.
As suspected found job names which violate the rules. For Ex: found these job names for https://cd.screwdriver.cd/pipelines/9
```
PR-147
PR-148
PR-149
PR-150
PR-151
PR-152
PR-153
PR-154
PR-155
PR-156
```

Will clean up database to delete these jobs.

**Comment by sagar1312** [comment]
Here is the DB migration to remove pull request jobs with invalid name
https://github.com/screwdriver-cd/data-schema/pull/495

**Pull request merged**
