### PR TITLE
fix: create PR jobs when new jobs added to the config in PR

### PR DESCRIPTION
**Pull request by minzcmu**
Removing  `const missingJobs = jobs.filter(j => missingJobNames.includes(j.name));`

We are only using `missingJobs.name` in the following calls. So there is no need to get the job objects. And this is giving side effect that when user adds a new job in PR, e.g. `new_main` and requires `~pr`, that PR job won't be created because it's filtered out by the above line.

### CODE REVIEW

**Comment by d2lam** [comment]
Any test change?

**Comment by minz1027** [comment]
@d2lam I can add a test to test the case I mentioned

**Comment by minz1027** [comment]
@d2lam addressed

**Review by tkyi — APPROVED** [review]

**Comment by minzcmu** [comment]
@d2lam test modified

**Review by d2lam — APPROVED** [review]

**Pull request merged**
