### PR TITLE
fix: PR event fails to create when author not found

### PR DESCRIPTION
**Pull request by petey**
Should fix the error that greenkeeper opens a PR in github and the webhook fails to create an event.

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
Eh, we should just be using the pipeline user, not the person who created the PR.

**Comment by petey** [comment]
Updated to use pipeline admin's token.

**Review by tkyi — APPROVED** [review]

**Review by stjohnjohnson — APPROVED** [review]
So much 👍

**Pull request merged**
