### PR TITLE
PR sync reads screwdriver yaml from its branch instead of master branch

### PR DESCRIPTION
**Pull request by d2lam**
Currently, PR build reads screwdriver.yaml from master branch. I think we can add this, then in webhooks, pass in the scmUrl: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/github.js#L208

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
@d2lam if you do this, then will the sync update all the jobs (even main job) to be based on that PR?

**Comment by d2lam** [comment]
@stjohnjohnson  That's true. What can we do so that it won't override but still works as expected? I can't think of a way unless we have a separate pipeline for it.

**Review by stjohnjohnson — CHANGES_REQUESTED** [review]
Will damage things. 👎

**Comment by d2lam** [comment]
@stjohnjohnson  We should discuss how to fix this. One way is when there is a change of screwdriver.yaml for a PR, then we create a separate pipeline for it and load from there instead. But that means the PR job will be in 2 pipelines (the master branch and its own branch). When the PR is closed then we delete that pipeline. But there are edge cases where we don't want to delete it. We need to go over this carefully but it seems complicated :(

**Pull request closed without merging**
