### PR TITLE
fix(1364): fix to consider ~pr:pipelineBranch trigger

### PR DESCRIPTION
**Pull request by yokawara**
## Context
Branch filtering doesn't work with `~pr` trigger when use pipeline's branch for the filter.

## Objective
Fix triggers like `~pr:pipelineBranch` to work properly.

## References
https://github.com/screwdriver-cd/screwdriver/issues/1364

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by yoshwata — APPROVED** [review]
LGTM

**Review by kkokufud — APPROVED** [review]
👍

**Comment by tk3fftk** [comment]
Do we need add tests?

**Comment by jithine** [comment]
Is this always the case or some corner case ? I've seen a case internally where for a job

```
jobs:
    qa:
        requires: [~pr:qa, ~commit:qa]
```

there are 2 pipelines Pipeline A on branch A & Pipeline B on branch B

A pull request on `qa` branch triggered only one of them

**Comment by yokawara** [comment]
@jithin1987 
This PR fixes PR branch filtering with pipeline's branch. (I fixed the Context to clearify the problem.)
This problem is caused because, we are removing branch when the branch is pipeline's branch in [api](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js#L341), but we don't consider pipeline's branch filtering after that.

In your case, `~pr:A` and `~pr:B` are supposed not to start builds on each pipelines.
> A pull request on qa branch triggered only one of them

~~I have not seen the case, there might be a new bug ... ?~~ I couldn't reproduce the case.
If it happenes regulary, I would like to work on it as another issue.

**Review by jithine — APPROVED** [review]

**Pull request merged**
